sources:
  - temp/UoqMunThenKhung-Regular.ufo
familyName: "UoqMunThenKhung"
removeOutlineOverlaps: false
extraFontmakeArgs: "--production-names"
autohintOTF: False
autohintTTF: False
buildWebfont: False